import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const desktopDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const errors = [];

function fail(message) {
  errors.push(message);
}

function readJson(relativePath) {
  const fullPath = path.join(desktopDir, relativePath);
  try {
    return JSON.parse(fs.readFileSync(fullPath, "utf8"));
  } catch (error) {
    fail(`${relativePath}: ${error.message}`);
    return {};
  }
}

function mustExist(relativePath) {
  if (!fs.existsSync(path.join(desktopDir, relativePath))) {
    fail(`${relativePath} is missing`);
  }
}

function mustContain(relativePath, needle) {
  const fullPath = path.join(desktopDir, relativePath);
  if (!fs.existsSync(fullPath)) {
    fail(`${relativePath} is missing`);
    return;
  }
  const text = fs.readFileSync(fullPath, "utf8");
  if (!text.includes(needle)) {
    fail(`${relativePath} does not contain ${needle}`);
  }
}

const pkg = readJson("package.json");

if (pkg.name !== "stackos-desktop") {
  fail("package name must be stackos-desktop");
}
if (pkg.main !== "src/main.js") {
  fail("package main must be src/main.js");
}
if (pkg.build?.productName !== "stackos") {
  fail("build.productName must be stackos");
}
if (pkg.build?.appId !== "io.stackos.desktop") {
  fail("build.appId must be io.stackos.desktop");
}
if (pkg.build?.publish) {
  fail("build.publish must be generated by scripts/build-mac.mjs from STACKOS_UPDATE_URL");
}

const targets = pkg.build?.mac?.target || [];
const targetNames = targets.map((target) => target.target);
if (!targetNames.includes("dmg") || !targetNames.includes("zip")) {
  fail("mac targets must include dmg and zip");
}

const extraResources = pkg.build?.extraResources || [];
const hasStackosPayload = extraResources.some(
  (entry) => entry.from === "payload/stackos" && entry.to === "stackos"
);
if (!hasStackosPayload) {
  fail("extraResources must include payload/stackos -> stackos");
}

for (const relativePath of [
  "src/main.js",
  "src/preload.js",
  "src/service.js",
  "src/updates.js",
  "scripts/build-stackos-payload.sh",
  "scripts/build-mac.mjs",
  "update-config.example.json"
]) {
  mustExist(relativePath);
}

mustContain("src/main.js", "contextIsolation: true");
mustContain("src/main.js", "nodeIntegration: false");
mustContain("src/main.js", "sandbox: true");
mustContain("src/service.js", "install");
mustContain("src/service.js", "--launchd");
mustContain("src/updates.js", "provider: \"generic\"");
mustContain("scripts/build-mac.mjs", "STACKOS_UPDATE_URL");
mustContain("scripts/build-mac.mjs", "update-config.json");

if (errors.length > 0) {
  console.error("desktop doctor failed:");
  for (const error of errors) {
    console.error(`- ${error}`);
  }
  process.exit(1);
}

console.log("desktop doctor ok");
