import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const desktopDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repoRoot = path.resolve(desktopDir, "..");
const errors = [];

function fail(message) {
  errors.push(message);
}

function readJson(relativePath) {
  const fullPath = path.join(desktopDir, relativePath);
  try {
    return JSON.parse(fs.readFileSync(fullPath, "utf8"));
  } catch (error) {
    fail(`${relativePath}: ${error.message}`);
    return {};
  }
}

function mustExist(relativePath) {
  if (!fs.existsSync(path.join(desktopDir, relativePath))) {
    fail(`${relativePath} is missing`);
  }
}

function mustContain(relativePath, needle) {
  const fullPath = path.join(desktopDir, relativePath);
  if (!fs.existsSync(fullPath)) {
    fail(`${relativePath} is missing`);
    return;
  }
  const text = fs.readFileSync(fullPath, "utf8");
  if (!text.includes(needle)) {
    fail(`${relativePath} does not contain ${needle}`);
  }
}

function readText(relativePath) {
  const fullPath = path.join(desktopDir, relativePath);
  try {
    return fs.readFileSync(fullPath, "utf8");
  } catch (error) {
    fail(`${relativePath}: ${error.message}`);
    return "";
  }
}

function readRootText(relativePath) {
  const fullPath = path.join(repoRoot, relativePath);
  try {
    return fs.readFileSync(fullPath, "utf8");
  } catch (error) {
    fail(`${relativePath}: ${error.message}`);
    return "";
  }
}

const pkg = readJson("package.json");
const pyprojectText = readRootText("pyproject.toml");
const stackosInitText = readRootText("stackos/__init__.py");
const pyprojectVersion = pyprojectText.match(/^version = "([^"]+)"$/m)?.[1] || null;
const stackosVersion = stackosInitText.match(/^__version__ = "([^"]+)"$/m)?.[1] || null;

if (pkg.name !== "stackos-desktop") {
  fail("package name must be stackos-desktop");
}
if (!/^\d+\.\d+\.\d+$/.test(pkg.version || "")) {
  fail("package version must be semver major.minor.patch");
}
if (!pyprojectVersion) {
  fail("pyproject.toml project.version is missing");
}
if (!stackosVersion) {
  fail("stackos/__init__.py __version__ is missing");
}
if (pkg.version !== pyprojectVersion || pkg.version !== stackosVersion) {
  fail("desktop/package.json, pyproject.toml, and stackos/__init__.py versions must match");
}
if (pkg.main !== "src/main.js") {
  fail("package main must be src/main.js");
}
if (pkg.build?.productName !== "StackOS") {
  fail("build.productName must be StackOS");
}
if (pkg.build?.appId !== "io.stackos.desktop") {
  fail("build.appId must be io.stackos.desktop");
}
if (pkg.build?.mac?.icon !== "assets/stackos-icon.icns") {
  fail("build.mac.icon must be assets/stackos-icon.icns");
}
if (pkg.build?.mac?.extendInfo?.CFBundleDisplayName !== "StackOS") {
  fail("build.mac.extendInfo.CFBundleDisplayName must be StackOS");
}
if (pkg.build?.mac?.extendInfo?.CFBundleName !== "StackOS") {
  fail("build.mac.extendInfo.CFBundleName must be StackOS");
}
if (pkg.build?.publish) {
  fail("build.publish must be generated by scripts/build-mac.mjs from STACKOS_UPDATE_URL");
}
if (pkg.build?.afterPack !== "scripts/sign-stackos-runtime-mac.cjs") {
  fail("build.afterPack must sign packaged StackOS runtime before final app signing");
}
if (pkg.build?.afterSign) {
  fail("build.afterSign must not re-sign the app after electron-builder notarization");
}

const targets = pkg.build?.mac?.target || [];
const targetNames = targets.map((target) => target.target);
if (!targetNames.includes("dmg") || !targetNames.includes("zip")) {
  fail("mac targets must include dmg and zip");
}
for (const target of targets) {
  const arches = target.arch || [];
  if (arches.length !== 1 || arches[0] !== "arm64") {
    fail("mac desktop targets must be arm64-only until x64 has a standalone Python payload");
  }
}

const extraResources = pkg.build?.extraResources || [];
const hasStackosPayload = extraResources.some(
  (entry) => entry.from === "payload/stackos" && entry.to === "stackos"
);
if (!hasStackosPayload) {
  fail("extraResources must include payload/stackos -> stackos");
}

for (const relativePath of [
  "assets/stackos-icon.icns",
  "assets/stackos-icon.png",
  "src/main.js",
  "src/preload.js",
  "src/service.js",
  "src/updates.js",
  "scripts/build-icons.mjs",
  "scripts/build-stackos-payload.sh",
  "scripts/build-mac.mjs",
  "scripts/sign-stackos-runtime-mac.cjs",
  "scripts/release-preflight.mjs",
  "scripts/test-updates.cjs",
  "scripts/test-build-mac-config.cjs",
  "update-config.example.json"
]) {
  mustExist(relativePath);
}

const uiFaviconPath = path.join(desktopDir, "..", "ui", "public", "favicon.png");
if (!fs.existsSync(uiFaviconPath)) {
  fail("ui/public/favicon.png is missing");
}

mustContain("src/main.js", "contextIsolation: true");
mustContain("src/main.js", "nodeIntegration: false");
mustContain("src/main.js", "sandbox: true");
mustContain("src/main.js", "readPackagedBuildInfo");
mustContain("src/service.js", "install");
mustContain("src/service.js", "--launchd");
mustContain("src/service.js", "--force");
mustContain("src/service.js", "installKey");
mustContain("src/service.js", "build-info.json");
mustContain("src/service.js", "packaged-missing");
mustContain("src/service.js", "PYTHONNOUSERSITE");
mustContain("src/service.js", "PLAYWRIGHT_BROWSERS_PATH");
mustContain("src/updates.js", "provider: \"generic\"");
mustContain("src/updates.js", "update endpoint must use HTTPS unless it is localhost for local testing");
mustContain("scripts/build-icons.mjs", "stackos-icon.png");
mustContain("scripts/build-icons.mjs", "iconutil");
mustContain("scripts/build-stackos-payload.sh", "build-info.json");
mustContain("scripts/build-stackos-payload.sh", "rsync -a");
mustContain("scripts/build-stackos-payload.sh", "PYTHONHOME");
mustContain("scripts/build-stackos-payload.sh", "PLAYWRIGHT_BROWSERS_PATH");
mustContain("scripts/build-stackos-payload.sh", "direct_url.json");
mustContain("scripts/build-stackos-payload.sh", "thin_payload_to_arm64");
mustContain("scripts/build-stackos-payload.sh", "PYTHONDONTWRITEBYTECODE");
mustContain("scripts/build-stackos-payload.sh", "python\" -B -m stackos");
mustContain("scripts/build-mac.mjs", "STACKOS_UPDATE_URL");
mustContain("scripts/build-mac.mjs", "STACKOS_REQUIRE_UPDATE_URL");
mustContain("scripts/build-mac.mjs", "STACKOS_DESKTOP_BUILD_DRY_RUN");
mustContain("scripts/build-mac.mjs", "STACKOS_UNSIGNED_DEV");
mustContain("scripts/build-mac.mjs", "identity: null");
mustContain("scripts/build-mac.mjs", "must use HTTPS unless it is localhost for local testing");
mustContain("scripts/build-mac.mjs", "scripts/build-stackos-payload.sh");
mustContain("scripts/build-mac.mjs", "scripts/build-icons.mjs");
mustContain("scripts/build-mac.mjs", "update-config.json");
mustContain("scripts/build-mac.mjs", "configuredDmgArches");
mustContain("scripts/sign-stackos-runtime-mac.cjs", "libpython.*\\.dylib");
mustContain("scripts/sign-stackos-runtime-mac.cjs", "developerIdIdentities");
mustContain("scripts/sign-stackos-runtime-mac.cjs", "Mach-O");
mustContain("scripts/sign-stackos-runtime-mac.cjs", "codesign");
mustContain("scripts/release-preflight.mjs", "Release preflight");
mustContain("package.json", "dist:mac:release");
mustContain("package.json", "STACKOS_REQUIRE_UPDATE_URL=1");
mustContain("package.json", "STACKOS_ALLOW_SIGNING_AUTO_DISCOVERY=1");
mustContain("package.json", "CSC_IDENTITY_AUTO_DISCOVERY=false");

if (errors.length > 0) {
  console.error("desktop doctor failed:");
  for (const error of errors) {
    console.error(`- ${error}`);
  }
  process.exit(1);
}

console.log("desktop doctor ok");
