import type { Component } from 'vue'
import {
  ArchiveBoxIcon,
  ArchiveBoxXMarkIcon,
  ArrowDownTrayIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingUpIcon,
  BanknotesIcon,
  Bars3Icon,
  BeakerIcon,
  BoltIcon,
  CalendarDaysIcon,
  ChartBarIcon,
  ChatBubbleLeftRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClipboardDocumentCheckIcon,
  ClockIcon,
  CodeBracketIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  CpuChipIcon,
  CubeIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  DocumentTextIcon,
  EllipsisHorizontalCircleIcon,
  EllipsisHorizontalIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FolderIcon,
  ForwardIcon,
  FunnelIcon,
  GlobeAltIcon,
  HomeIcon,
  InboxIcon,
  InformationCircleIcon,
  KeyIcon,
  LifebuoyIcon,
  LightBulbIcon,
  LinkIcon,
  ListBulletIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  MegaphoneIcon,
  MoonIcon,
  NewspaperIcon,
  NoSymbolIcon,
  PauseCircleIcon,
  PlayCircleIcon,
  PlusIcon,
  PowerIcon,
  PuzzlePieceIcon,
  QueueListIcon,
  RectangleStackIcon,
  ShareIcon,
  ShieldCheckIcon,
  SparklesIcon,
  Squares2X2Icon,
  SunIcon,
  TrashIcon,
  UserGroupIcon,
  WrenchScrewdriverIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/vue/24/outline'

/**
 * Central icon registry — the only place icon components enter the app.
 * Keys are stable kebab-case names; several are aliases kept for the status
 * registry in `design/status.ts`. Render through `UiIcon`.
 */
export const UI_ICONS: Record<string, Component> = {
  // Actions
  ban: NoSymbolIcon,
  check: CheckIcon,
  close: XMarkIcon,
  copy: DocumentDuplicateIcon,
  'external-link': ArrowTopRightOnSquareIcon,
  eye: EyeIcon,
  'eye-off': EyeSlashIcon,
  filter: FunnelIcon,
  menu: Bars3Icon,
  more: EllipsisHorizontalIcon,
  plus: PlusIcon,
  refresh: ArrowPathIcon,
  'rotate-ccw': ArrowPathIcon,
  save: ArrowDownTrayIcon,
  search: MagnifyingGlassIcon,
  trash: TrashIcon,

  // Chevrons / arrows
  'arrow-right': ArrowRightIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'chevron-up-down': ChevronUpDownIcon,

  // Status (aliases for design/status.ts icon names)
  'alert-octagon': ExclamationCircleIcon,
  'alert-triangle': ExclamationTriangleIcon,
  archive: ArchiveBoxIcon,
  'archive-x': ArchiveBoxXMarkIcon,
  'check-circle': CheckCircleIcon,
  circle: EllipsisHorizontalCircleIcon,
  'circle-check': CheckCircleIcon,
  'circle-dashed': EllipsisHorizontalCircleIcon,
  'circle-slash': NoSymbolIcon,
  clock: ClockIcon,
  file: DocumentIcon,
  'flask-conical': BeakerIcon,
  gauge: ChartBarIcon,
  info: InformationCircleIcon,
  'key-round': KeyIcon,
  loader: ArrowPathIcon,
  lock: LockClosedIcon,
  'octagon-alert': ExclamationCircleIcon,
  pause: PauseCircleIcon,
  plug: PowerIcon,
  'skip-forward': ForwardIcon,
  'timer-off': ClockIcon,
  'trending-up': ArrowTrendingUpIcon,
  'x-circle': XCircleIcon,

  // Navigation / domain
  banknotes: BanknotesIcon,
  beaker: BeakerIcon,
  bolt: BoltIcon,
  calendar: CalendarDaysIcon,
  'chart-bar': ChartBarIcon,
  chat: ChatBubbleLeftRightIcon,
  chip: CpuChipIcon,
  'code-bracket': CodeBracketIcon,
  cube: CubeIcon,
  database: CircleStackIcon,
  'file-text': DocumentTextIcon,
  folder: FolderIcon,
  'git-branch': ShareIcon,
  globe: GlobeAltIcon,
  grid: Squares2X2Icon,
  home: HomeIcon,
  inbox: InboxIcon,
  key: KeyIcon,
  library: RectangleStackIcon,
  lifebuoy: LifebuoyIcon,
  'light-bulb': LightBulbIcon,
  link: LinkIcon,
  list: ListBulletIcon,
  megaphone: MegaphoneIcon,
  newspaper: NewspaperIcon,
  'plug-zap': BoltIcon,
  puzzle: PuzzlePieceIcon,
  'queue-list': QueueListIcon,
  runs: PlayCircleIcon,
  settings: Cog6ToothIcon,
  'shield-check': ShieldCheckIcon,
  sparkles: SparklesIcon,
  tasks: ClipboardDocumentCheckIcon,
  terminal: CommandLineIcon,
  users: UserGroupIcon,
  wrench: WrenchScrewdriverIcon,

  // Theme
  moon: MoonIcon,
  sun: SunIcon,
}

export function iconComponent(name: string | undefined | null): Component | undefined {
  return name ? UI_ICONS[name] : undefined
}

export function hasIcon(name: string | undefined | null): boolean {
  return Boolean(iconComponent(name))
}
